general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 300
    on-timeout = ~/.local/share/hyprarch/shell/brightness.sh save && ~/.local/share/hyprarch/shell/brightness.sh set 20
    on-resume = ~/.local/share/hyprarch/shell/brightness.sh restore
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}
