general {
    lock_cmd = pidof hyprlock || hyprlock
    unlock_cmd = hyprctl dispatch dpms on
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 150
    on-timeout = ~/.local/share/hyprarch/shell/brightness.sh save && ~/.local/share/hyprarch/shell/brightness.sh set 10
    on-resume = ~/.local/share/hyprarch/shell/brightness.sh restore
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}